---
title: "SOCS0100 - Computational Social Science"
format:
  html:
    include-before-body: helpers/remove-nav.html
    include-after-body: helpers/remove-title.html
---

# 📑 Module Brief

This module will provide students with computational and reproducible research tools that are frequently used in social data science. It will first introduce students to how to use RStudio and GitHub together as a toolkit for reproducible social science research, illustrating key features of R packages for managing data and conducting data analysis. Second, students will learn the fundamentals of functional programming, including conditional flow (e.g. if-else conditionals) and creating functions to automate common tasks in data wrangling and visualisation. Students will also learn how these techniques can be used to make data science workflows more efficient, transparent, and reproducible. Third, students will be introduced to the principles of ethical web scraping and will learn how to collect data from both static and dynamic webpages. Fourth, students will learn how to build and deploy Shiny apps to create interactive data visualisations and disseminate research findings. Students will also learn how to work with APIs to collect and exchange data programmatically. Finally, students will be introduced to generative artificial intelligence and AI agents as emerging tools for computational social science. They will learn how open-weight large language models can interact with computational tools, assist with data science workflows, and support the automation of tasks such as data collection, data processing, analysis, and the development of research outputs. Particular attention will be given to the reproducibility, reliability, ethical use, and critical evaluation of AI-assisted research workflows. Therefore, by the end of the module, students should be able to contribute to reproducible social science research projects involving automated data collection, data processing and analysis, interactive dissemination, and AI-assisted computational workflows, while managing projects and collaborating through a source-code repository. 

# 🎯 Learning Objectives

After completing the module students should be able to: - Familiarised with foundations and applications of social data science

-   Equipped with the skills to understand computational tools for reproducible research

-   Aware of the potential and pitfalls of social data science

-   Able to collaborate in reproducible research projects, using a source-code repository

------------------------------------------------------------------------

**Select Academic Year/Term:**

<a href="2026/index.qmd"> <button class="button-61">2026/27</button> </a>
